const colorKey = {
    background: '#222',
    background_bright: '#333',
    component: '#000',
    component_preview: '#0006',
    component_text: '#fff',
    component_text_preview: '#fff6',
    component_connection: '#fff',
    component_connection_connect: '#00f',
    component_connection_connect_preview: '#00f6',
    component_remove: '#f006',
    wire_grid_point: '#f006',
    wire: '#666',
    wire_on: '#0f0',
    wire_off: '#f00',
    wire_route: '#66f',
    wire_route_preview: '#66f6',
    wire_route_point: '#00f',
    wire_route_point_preview: '#00f6',
    wire_remove: '#f00',
}